// <auto-generated />
using System;
using CricketLive.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CricketLive.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CricketLiveDbContext))]
    [Migration("20260929182733_AddTeamColumns")]
    partial class AddTeamColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CricketLive.Infrastructure.Persistence.ArchivedMatch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayTeamId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeTeamId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesName")
                        .HasDatabaseName("ix_archived_matches_series");

                    b.HasIndex("StartTimeUtc")
                        .HasDatabaseName("ix_archived_matches_start_time");

                    b.HasIndex("AwayTeamId", "StartTimeUtc")
                        .HasDatabaseName("ix_archived_matches_away_team");

                    b.HasIndex("HomeTeamId", "StartTimeUtc")
                        .HasDatabaseName("ix_archived_matches_home_team");

                    b.HasIndex("SeriesId", "StartTimeUtc")
                        .HasDatabaseName("ix_archived_matches_series_id");

                    b.ToTable("archived_matches", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
