// <auto-generated />
using System;
using CricketLive.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CricketLive.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CricketLiveDbContext))]
    [Migration("20261001203120_AddArchivedMatchScope")]
    partial class AddArchivedMatchScope
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CricketLive.Infrastructure.Persistence.ArchivedMatch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AwayTeamId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("HomeTeamId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("InScope")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeriesId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeriesName")
                        .HasDatabaseName("ix_archived_matches_series");

                    b.HasIndex("StartTimeUtc")
                        .HasDatabaseName("ix_archived_matches_start_time");

                    b.HasIndex("AwayTeamId", "StartTimeUtc")
                        .HasDatabaseName("ix_archived_matches_away_team");

                    b.HasIndex("HomeTeamId", "StartTimeUtc")
                        .HasDatabaseName("ix_archived_matches_home_team");

                    b.HasIndex("InScope", "StartTimeUtc")
                        .HasDatabaseName("ix_archived_matches_scope");

                    b.HasIndex("SeriesId", "StartTimeUtc")
                        .HasDatabaseName("ix_archived_matches_series_id");

                    b.ToTable("archived_matches", (string)null);
                });

            modelBuilder.Entity("CricketLive.Infrastructure.Persistence.BackfillState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("LapsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("NextOffset")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PagesReadOn")
                        .HasColumnType("date");

                    b.Property<int>("PagesReadToday")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("backfill_state", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
